
services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - appnet
    command: sleep infinity
    ports:
      - "5000:8080"
      - "5005:5005"
      - "7015:7015"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Username=postgres;Password=postgres;Database=mydb
      - Redis__Host=redis
    depends_on:
      - db
      - redis
    working_dir: /workspace

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
